name: Build

on:
  pull_request:
  merge_group:
  push:
    branches:
      - develop
    tags:
      - '*'
env:
  DOCKER_IMAGE_NAME: tools4homeautomation/solix-exporter

jobs:
  build:
    name: 'Build and Test on Node ${{ matrix.node_version }} and ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        node_version:
          - 22
          # renovate: datasource=docker depName=node
          - 24
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v6
      - name: 'Use Node.js ${{ matrix.node_version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node_version }}'
      - name: npm build and test
        run: |
          npm run clean
          npm run build
          npm run test

  end2end:
    name: 'End2End Test on Node ${{ matrix.node_version }} and ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        node_version:
          # Can not run in parallel due to Anker login limiting
          # renovate: datasource=docker depName=node
          - 24
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: 'Use Node.js ${{ matrix.node_version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node_version }}'
      - name: npm test
        run: |
          npm run clean
          npm run e2e
        env:
          ANKER_USERNAME: ${{ vars.ANKER_E2E_USER }}
          ANKER_PASSWORD: ${{ secrets.ANKER_E2E_PASS }}
          ANKER_COUNTRY: ${{ vars.ANKER_E2E_COUNTRY }}
          DEVICE_SN: ${{ secrets.ANKER_E2E_DEVICE_SN }}
          GH_BRANCH: ${{ github.head_ref || github.ref_name }}

  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          # renovate: datasource=docker depName=node
          node-version: '24'
      - name: 'Build Package'
        run: |
          npm run clean
          npm run build

      - name: Write version vars
        run: |
          BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
          BRANCH=${GITHUB_REF_NAME#v}
          APP_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | sed 's/ //g')
          echo Version: $APP_VERSION
          echo "VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{env.DOCKER_IMAGE_NAME}}:next
          build-args: |
            BUILD_DATE=${{env.BUILD_DATE}}
            APP_VERSION=${{env.APP_VERSION}}
          platforms: linux/amd64,linux/arm64

      - name: Push To Docker Hub
        id: push-to-dockerhub-preview
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{env.DOCKER_IMAGE_NAME}}:next
            ${{env.DOCKER_IMAGE_NAME}}:${{env.APP_VERSION}}_rc
          build-args: |
            BUILD_DATE=${{env.BUILD_DATE}}
            APP_VERSION=${{env.APP_VERSION}}
          platforms: linux/amd64,linux/arm64
        if: github.ref == 'refs/heads/develop'

      - name: Push To Docker Hub
        id: push-to-dockerhub-tagged
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{env.DOCKER_IMAGE_NAME}}:latest
            ${{env.DOCKER_IMAGE_NAME}}:${{env.BRANCH}}
          build-args: |
            BUILD_DATE=${{env.BUILD_DATE}}
            APP_VERSION=${{env.BRANCH}}
          platforms: linux/amd64,linux/arm64
        if: github.ref_type == 'tag' || github.tag != ''

  build-results:
    name: Build results
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build
      - end2end
      - package
    steps:
      - run: exit 1
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
                || contains(needs.*.result, 'skipped')
                }}
